---

- hosts: localhost
  connection: local
  gather_facts: False
  
  
  tasks:
    - name: provision instances
      ec2:
         key_name: sev-test
         group: launch-wizard-3
         instance_type: t2.micro
         ec2_region: eu-west-1
         image: "ami-f95ef58a"
         wait: true
         instance_tags:
            Name: Eip-Demo
         exact_count: 2
         count_tag: Eip-Demo
      register: ec2

    - name: Add the newly created EC2 instance(s) to the local host group
      local_action: lineinfile 
                      dest="./hosts" 
                      regexp={{ item.public_ip }} 
                      insertafter="[all]" line={{ item.public_ip }}
      with_items: ec2.instances

    - name: wait for SSH to come up
      local_action: wait_for
                     host={{ item.public_dns_name }}
                     port=22 delay=10 timeout=180 state=started
      with_items: ec2.instances

    - name: install apache2
      local_action: apt pkg=apache2 state=latest
      with_items: ec2.instances
    - name: start apache
      local_action: service name=apache2 state=started
      with_items: ec2.instances

    - name: install git
      local_action: apt pkg=git state=latest
      with_items: ec2.instances

